db-management:
  csv-file-path: C:/Users/vsark/Documents/db-site/cross-verified-database.csv
  import:
    relational-all: false
    raw-all: false
  process:
    citizenship-names:
      readability: false
      search: false
    person-names:
      search: true