spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migration
logging:
  file:
    path: logs
  level:
    ROOT: INFO
db-management:
  csv-file-path: no-file
  import:
    all: false
  process:
    citizenship-names:
      readability: false
      search: false
    person-names:
      search: false
exporting:
  path: exported
search:
  results-per-page: 1000