spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbpaperdb
    username: vlatko
    password: vlatko
logging:
  file:
    path: logs
  level:
    ROOT: INFO
db-management:
  csv-file-path: /static/cross-verified-database.csv
