spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migration
logging:
  file:
    path: logs
  level:
    ROOT: INFO
db-management:
  csv-file-path: no-file
  threading:
    multithreaded: true
    threads: 16
    queue-capacity: 500
  log:
    update-interval: 100000
  actions:
    import:
      all: false
    process:
      citizenship-names:
        readability: false
        search: false
      person-names:
        search: false
exporting:
  path: exported
  csv:
    header: classpath:/static/header.csv
  job:
    lifetime: 10
search:
  results-per-page: 1000