spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migration
logging:
  file:
    path: bin/logs
  level:
    ROOT: INFO
db-management:
  csv-file-path: no-file
  threading:
    multithreaded: true
    threads: 16
    queue-capacity: 500
  log:
    update-interval: 100000
  actions:
    import:
      all: false
    process:
      citizenship-names:
        readability: false
        search: false
      person-names:
        search: false
exporting:
  path: bin/exported
  included: classpath:static/included/*
  csv:
    header: classpath:static/header.csv
  job:
    lifetime: 10
temp:
  path: bin/temp
search:
  results-per-page: 200
timeline:
  result-limit: 80000
wikidata-codes:
  max-persons: 100